/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Benjamin Bardou (https://sketchfab.com/meryon)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/diane-iv-louvre-museum-low-definition-84dbfc59f41a4ceaa71be6cce3bc3899
title: Diane IV - Louvre Museum (Low Definition)
*/

import { OrbitControls } from "@react-three/drei";
import { useRef } from "react";

function ModelWrapper({ children, orbitOffset }) {
  const group = useRef();

  return (
    <>
      <group ref={group} dispose={null}>
        {children}
      </group>
      <OrbitControls
        enableDamping={true}
        dampingFactor={0.1}
        enableZoom={false}
        enablePan={false}
        autoRotate={true}
        autoRotateSpeed={0.5}
        target={orbitOffset}
        minPolarAngle={Math.PI / 2}
        maxPolarAngle={Math.PI / 2}
        cursor={true}
      />
    </>
  );
}

export default ModelWrapper;