/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Geoffrey Marchal (https://sketchfab.com/geoffreymarchal)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/the-emperor-augustus-d958f8c6de0c4fd8bc5226b3d18abf2d
title: The Emperor Augustus
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import augustus from './binary/augustus.glb';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(augustus);
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-7.3, -0.55, -7.3]} rotation={[0, -0.06, -1.55]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={nodes.Object_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={nodes.Object_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={nodes.Object_4.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/augustus.glb");
