/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Benjamin Bardou (https://sketchfab.com/meryon)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/diane-iv-louvre-museum-low-definition-84dbfc59f41a4ceaa71be6cce3bc3899
title: Diane IV - Louvre Museum (Low Definition)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import diane from "./binary/diane.glb";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(diane);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 10]}>
        <group position={[-2.83, -2.95, -1.21]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_3.geometry}
            material={materials.lambert6SG}
          ></mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/diane.glb");
