/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: HoangHiepVu (https://sketchfab.com/HoangHiepVu)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/louis-xiv-de-france-louvre-paris-a0cc0e7eee384c99838dff2857b8158c
title: Louis XIV de France, Louvre, Paris
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import louis from './binary/louis-xiv.glb';

export default function Model(props) {
  const group = useRef();
  const { nodes } = useGLTF(louis);
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 9, -2.25]} rotation={[-Math.PI, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={nodes.Object_5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={nodes.Object_6.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={nodes.Object_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={nodes.Object_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={nodes.Object_4.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/louis-xiv.glb");