/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Benjamin Bardou (https://sketchfab.com/meryon)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/philopoemen-louvre-museum-f21d998c67774d10855def0003854c08
title: Philopoemen - Louvre Museum
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import philopoemen from '../../assets/models/philopoemen.glb';

export default function Model(props) {
    const group = useRef();
    const { nodes } = useGLTF(philopoemen);
    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, Math.PI / 2 + 0.8]}>
                <group position={[-58.97, -62.74, -24.2]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_3.geometry}
                        material={nodes.Object_3.material}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_4.geometry}
                        material={nodes.Object_4.material}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_5.geometry}
                        material={nodes.Object_5.material}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_6.geometry}
                        material={nodes.Object_6.material}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_7.geometry}
                        material={nodes.Object_7.material}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_8.geometry}
                        material={nodes.Object_8.material}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/philopoemen.glb");