/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Geoffrey Marchal (https://sketchfab.com/geoffreymarchal)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/the-three-graces-437574a871ca4e56be5944d5f0390309
title: The Three Graces
*/

import { useGLTF } from '@react-three/drei';
import React, { useRef } from 'react';
import graces from '../../assets/models/three-graces.glb';

export default function Model(props) {
  const group = useRef();
  const { nodes } = useGLTF(graces);
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-3.94, -20.05, 9.07]} rotation={[-0.04, -0.65, -3.13]}>
        <group position={[-8.92, -24.14, -5.58]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_2.geometry}
            material={nodes.Object_2.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_3.geometry}
            material={nodes.Object_3.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={nodes.Object_4.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_5.geometry}
            material={nodes.Object_5.material}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/three-graces.glb');
